start Nearest%~dp0Neighbor.exe
start Nearest%~dp0Neighbor.exe
start Nearest%~dp0Neighbor.exe
start Nearest%~dp0Neighbor.exe
start Nearest%~dp0Neighbor.exe
start Nearest%~dp0Neighbor.exe
start Nearest%~dp0Neighbor.exe
start Nearest%~dp0Neighbor.exe
start Nearest%~dp0Neighbor.exe
start Nearest%~dp0Neighbor.exe